export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-gray-950 text-white px-6 py-12">
      <div className="max-w-4xl mx-auto">

        <h1 className="text-4xl font-bold mb-8">
          Terms of Service
        </h1>

        <p className="text-gray-400 mb-8">
          Last Updated: May 2026
        </p>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-3">
            Acceptance of Terms
          </h2>

          <p className="text-gray-300">
            By accessing or using MCP AI Assistant, you agree to be bound
            by these Terms of Service. If you do not agree with any part
            of these terms, you should not use the application.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-3">
            Description of Service
          </h2>

          <p className="text-gray-300">
            MCP AI Assistant is an AI-powered productivity platform that
            enables users to manage emails, calendar events, perform web
            searches, and interact with connected tools using natural
            language commands.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-3">
            User Responsibilities
          </h2>

          <ul className="list-disc ml-6 mt-3 text-gray-300 space-y-2">
            <li>Provide accurate account information.</li>
            <li>Maintain the security of your Google account.</li>
            <li>Use the service in compliance with applicable laws.</li>
            <li>Not misuse, abuse, or attempt to disrupt the service.</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-3">
            Google Account Access
          </h2>

          <p className="text-gray-300">
            MCP AI Assistant uses Google OAuth authentication to access
            Gmail and Google Calendar features only after explicit user
            authorization.
          </p>

          <p className="text-gray-300 mt-4">
            Users may revoke access at any time through their Google
            Account security settings.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-3">
            Acceptable Use
          </h2>

          <p className="text-gray-300">
            Users agree not to:
          </p>

          <ul className="list-disc ml-6 mt-3 text-gray-300 space-y-2">
            <li>Use the service for unlawful activities.</li>
            <li>Attempt unauthorized access to any system.</li>
            <li>Interfere with the operation of the application.</li>
            <li>Use the platform to distribute harmful content.</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-3">
            Intellectual Property
          </h2>

          <p className="text-gray-300">
            All software, branding, and content associated with MCP AI
            Assistant remain the property of the application owner unless
            otherwise stated.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-3">
            Disclaimer
          </h2>

          <p className="text-gray-300">
            The service is provided on an "as is" and "as available"
            basis. We do not guarantee uninterrupted operation,
            completeness, or accuracy of responses generated by the AI.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-3">
            Limitation of Liability
          </h2>

          <p className="text-gray-300">
            MCP AI Assistant shall not be liable for any direct,
            indirect, incidental, or consequential damages resulting
            from the use or inability to use the service.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-3">
            Changes to These Terms
          </h2>

          <p className="text-gray-300">
            We reserve the right to update or modify these Terms of
            Service at any time. Continued use of the application after
            changes are posted constitutes acceptance of those changes.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-3">
            Contact Information
          </h2>

          <p className="text-gray-300">
            If you have any questions regarding these Terms of Service,
            please contact:
          </p>

          <p className="text-blue-400 mt-3">
            abhisonijeet123@gmail.com
          </p>
        </section>

      </div>
    </div>
  );
}